name: tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge, defaults
        channel-priority: true
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
    - shell: bash -l {0}
      run: |
        mamba install -y -c conda-forge gdal=3.1.2
        pip install poetry==1.1.3
        # Make poetry use current conda environment
        # https://github.com/python-poetry/poetry/issues/105
        poetry config virtualenvs.path $(conda info --base)/envs
        poetry config virtualenvs.create 0
        poetry install
        poetry run flake8 src tests noxfile.py
        poetry run pytest --doctest-modules src tests
