name: tests
on:
  push:
    paths-ignore:
    - '**.md'
    - 'docs/**'
    - '.gitignore'
    - '.pre-commit-config.yaml'
jobs:
  tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ''
        auto-activate-base: true
        auto-update-conda: true
        channels: conda-forge
        channel-priority: true
        mamba-version: '*'
    - name: Install make on windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: |
        choco install make
        make --version
    - name: Install make on mac and linux
      if: matrix.os != 'windows-latest'
      shell: bash -l {0}
      run: |
        mamba install -y make
        make --version
    - name: Install python
      shell: bash -l {0}
      run: |
        mamba install -y python=${{ matrix.python-version }}
        python --version
    - name: Install poetry
      shell: bash -l {0}
      run: |
        mamba install -y poetry=1.1.3
        poetry --version
    - name: Install gdal
      shell: bash -l {0}
      run: |
        mamba install -y gdal=3.2.0
        gdalinfo --version
    - name: Run tests
      shell: bash -l {0}
      run: |
        # HACK: Install project into a conda environment with gdal already installed
        poetry config virtualenvs.path $(conda info --base)/envs
        poetry config virtualenvs.create 0
        poetry install
        make lint
        make test
